name: Build Android APK (Flet)

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Setup Java (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Check Flutter / Flet
        run: |
          flutter --version
          flutter doctor -v || true
          python -c "import flet; print('flet', flet.__version__)"
      
      - name: Build APK (signed if keystore provided)
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          set -e
          echo "BUILD_NUMBER=$BUILD_NUMBER, BUILD_VERSION=$BUILD_VERSION"
          if [ -n "$ANDROID_KEYSTORE_BASE64" ]; then
            echo "Keystore provided → decoding and using it to sign the APK"
            echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android.keystore
            flet build apk --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION \
              --android-signing-key-store android.keystore \
              --android-signing-key-alias "$ANDROID_KEY_ALIAS" \
              --android-signing-key-store-password "$ANDROID_KEYSTORE_PASSWORD" \
              --android-signing-key-password "$ANDROID_KEY_PASSWORD"
          else
            echo "No keystore secret found → building release APK (unsigned or signed by Flet default)."
            flet build apk --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/apk
          if-no-files-found: warn
